"""Storage-independent, immutable descriptions of two-dimensional image products.

These descriptors contain data semantics, not display state or biological truth.
They neither require physical calibration nor impose the narrower TIFF write policy.
"""
from __future__ import annotations

import math
from collections.abc import Mapping
from dataclasses import dataclass
from numbers import Integral
from types import MappingProxyType
from typing import Any

import numpy as np

from .pixel_size import PixelSize
from .spec import ImageType


def integer(value: object, name: str, *, minimum: int = 0) -> int:
    if isinstance(value, (bool, np.bool_)) or not isinstance(value, Integral):
        raise TypeError(f"{name} must be an integer")
    result = int(value)
    if result < minimum:
        raise ValueError(f"{name} must be at least {minimum}")
    return result


def _shape(value: tuple[int, ...], axes: str) -> tuple[int, ...]:
    result = tuple(integer(v, "shape dimension", minimum=1) for v in value)
    if axes not in {"YX", "CYX", "YXS"} or len(result) != len(axes):
        raise ValueError(f"Expected YX, CYX, or YXS geometry, found {axes!r} {result}")
    return result


def _freeze_channel_metadata(value: Any, ancestors: tuple[int, ...] = ()) -> Any:
    """Snapshot data-only metadata without retaining mutable caller-owned values."""
    if value is None or type(value) in (bool, int, float, str):
        return value
    if not isinstance(value, (Mapping, list, tuple)):
        raise TypeError(
            "channel_metadata values must be None, bool, int, float, str, "
            "string-keyed mappings, lists, or tuples"
        )
    identity = id(value)
    if identity in ancestors:
        raise ValueError("channel_metadata must not contain reference cycles")
    if len(ancestors) >= 64:
        raise ValueError("channel_metadata must not exceed 64 nested containers")
    ancestors = (*ancestors, identity)
    if isinstance(value, Mapping):
        if any(type(key) is not str for key in value):
            raise TypeError("channel_metadata mapping keys must be plain strings")
        return MappingProxyType({
            key: _freeze_channel_metadata(item, ancestors) for key, item in value.items()
        })
    return tuple(_freeze_channel_metadata(item, ancestors) for item in value)


@dataclass(frozen=True, slots=True)
class ImageLevel:
    """One resolution, using level-local pixel-edge coordinates and half-open bounds.

    ``downsample_yx`` is an explicitly known sampling scale relative to level zero,
    NOT the ratio of rounded raster dimensions. None means unknown. All levels
    share an origin and axis directions; arbitrary registration is not modeled.
    """

    index: int
    axes: str
    shape: tuple[int, ...]
    pixel_size: PixelSize | None = None
    downsample_yx: tuple[float, float] | None = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "index", integer(self.index, "level index"))
        object.__setattr__(self, "shape", _shape(self.shape, self.axes))
        if self.pixel_size is not None and not isinstance(self.pixel_size, PixelSize):
            raise TypeError("pixel_size must be a PixelSize or None")
        scale = self.downsample_yx
        if self.index == 0 and scale is None:
            scale = (1.0, 1.0)
        if scale is not None:
            if len(scale) != 2 or any(
                isinstance(v, (bool, np.bool_)) or not math.isfinite(v) or v < 1 for v in scale
            ):
                raise ValueError("downsample_yx requires two finite scales >= 1")
            scale = tuple(float(v) for v in scale)
            if self.index == 0 and scale != (1.0, 1.0):
                raise ValueError("Level zero must have downsample_yx=(1, 1)")
        object.__setattr__(self, "downsample_yx", scale)

    @property
    def spatial_shape(self) -> tuple[int, int]:
        return self.shape[self.axes.index("Y")], self.shape[self.axes.index("X")]


@dataclass(frozen=True, slots=True)
class ImageMetadata:
    """One image's canonical axes, sample type, channel identity, and resolutions.

    Channels are logical channels: RGB has one logical channel and three samples.
    Labels are categorical YX integers. Duplicate names are permitted, but name
    lookup must reject ambiguity. Missing IDs are generated by image wrappers.
    Metadata discovery must not read pixels. No path, display range, or assumed
    acquisition facts are required. Channel metadata is a recursively immutable
    snapshot of plain scalar values, string-keyed mappings, and lists/tuples;
    mappings become read-only proxies and sequences become tuples. Unsupported
    objects and reference cycles are rejected instead of retained by reference.
    """

    axes: str
    shape: tuple[int, ...]
    dtype: np.dtype
    image_type: ImageType = "multichannel"
    channel_names: tuple[str, ...] | None = None
    pixel_size: PixelSize | None = None
    levels: tuple[ImageLevel, ...] = ()
    channel_ids: tuple[str | None, ...] | None = None
    icc_profile: bytes | None = None
    background_label: int = 0
    channel_source_ids: tuple[str | None, ...] | None = None
    channel_metadata: tuple[Mapping[str, Any], ...] | None = None

    def __post_init__(self) -> None:
        shape = _shape(self.shape, self.axes)
        dtype = np.dtype(self.dtype).newbyteorder("=")
        if dtype.kind not in "buif":
            raise TypeError("Image dtype must be real numeric or boolean, not object/complex")
        if self.image_type not in {"multichannel", "rgb", "label"}:
            raise ValueError("image_type must be 'multichannel', 'rgb', or 'label'")
        if self.pixel_size is not None and not isinstance(self.pixel_size, PixelSize):
            raise TypeError("pixel_size must be a PixelSize or None")
        if self.image_type == "rgb":
            if self.axes != "YXS" or shape[-1] != 3:
                raise ValueError("RGB images require YXS with exactly three samples")
            count, defaults = 1, ("RGB",)
        elif self.image_type == "label":
            if self.axes != "YX" or dtype.kind not in "ui":
                raise ValueError("Label images require one integer YX raster")
            count, defaults = 1, ("Labels",)
        else:
            if self.axes not in {"YX", "CYX"}:
                raise ValueError("Multichannel images require YX or CYX, not inferred RGB")
            count = shape[0] if self.axes == "CYX" else 1
            defaults = tuple(f"Channel {i + 1}" for i in range(count))
        if isinstance(self.channel_names, (str, bytes)):
            raise TypeError("channel_names must be a sequence of names, not a string")
        if isinstance(self.channel_ids, (str, bytes)):
            raise TypeError("channel_ids must be a sequence of IDs, not a string")
        names = defaults if self.channel_names is None else tuple(self.channel_names)
        if len(names) != count or any(not isinstance(n, str) or not n.strip() for n in names):
            raise ValueError(f"Expected {count} nonempty logical channel names")
        ids = (None,) * count if self.channel_ids is None else tuple(self.channel_ids)
        if len(ids) != count or any(
            i is not None and (not isinstance(i, str) or not i.strip()) for i in ids
        ):
            raise ValueError(
                "channel_ids must align with channels and contain nonempty IDs or None"
            )
        source_ids = ids if self.channel_source_ids is None else tuple(self.channel_source_ids)
        if len(source_ids) != count or any(
            (v is not None and not isinstance(v, str) for v in source_ids),
        ):
            raise ValueError("channel_source_ids must align with the logical channels")
        records = self.channel_metadata
        if records is None:
            records = ({},) * count
        if len(records) != count or any(not isinstance(v, Mapping) for v in records):
            raise ValueError("channel_metadata must align with the logical channels")
        object.__setattr__(self, "channel_source_ids", source_ids)
        object.__setattr__(self, "channel_metadata", tuple(
            _freeze_channel_metadata(record) for record in records
        ))
        # Include generated IDs when checking collisions.
        resolved_ids = tuple(v if v is not None else f"Channel:0:{i}" for i, v in enumerate(ids))
        if len(set(resolved_ids)) != count:
            raise ValueError("Channel IDs, including generated IDs, must be unique")
        if self.icc_profile is not None and self.image_type != "rgb":
            raise ValueError("ICC profiles are only valid for RGB images")
        if self.icc_profile is not None and not isinstance(self.icc_profile, (bytes, bytearray)):
            raise TypeError("icc_profile must contain bytes")
        if isinstance(self.background_label, (bool, np.bool_)) or not isinstance(
            self.background_label, Integral
        ):
            raise TypeError("background_label must be an integer")
        background = int(self.background_label)
        if self.image_type == "label":
            limits = np.iinfo(dtype)
            if not limits.min <= background <= limits.max:
                raise ValueError("background_label must fit the label dtype")
        elif background != 0:
            raise ValueError("background_label is only meaningful for label images")
        levels = tuple(self.levels) or (ImageLevel(0, self.axes, shape, self.pixel_size),)
        for i, level in enumerate(levels):
            if not isinstance(level, ImageLevel) or level.index != i or level.axes != self.axes:
                raise ValueError(
                    "Levels must be ImageLevels with contiguous indices and common axes"
                )
            if any(level.shape[k] != shape[k] for k, a in enumerate(self.axes) if a not in "YX"):
                raise ValueError("All levels must preserve channel/sample dimensions")
            if i and any(a > b for a, b in zip(level.spatial_shape, levels[i - 1].spatial_shape)):
                raise ValueError("Pyramid spatial dimensions must not increase")
            if self.pixel_size is not None and level.pixel_size is not None:
                base = self.pixel_size.converted_to("µm")
                current = level.pixel_size.converted_to("µm")
                actual = (current.y / base.y, current.x / base.x)
                if level.downsample_yx is not None and not all(
                    math.isclose(a, b, rel_tol=1e-5, abs_tol=0)
                    for a, b in zip(actual, level.downsample_yx)
                ):
                    raise ValueError("Level calibration disagrees with its declared sampling scale")
        if levels[0].shape != shape or levels[0].pixel_size != self.pixel_size:
            raise ValueError("Level zero geometry/calibration must equal the image descriptor")
        object.__setattr__(self, "shape", shape)
        object.__setattr__(self, "dtype", dtype)
        object.__setattr__(self, "channel_names", names)
        object.__setattr__(self, "channel_ids", ids)
        object.__setattr__(self, "levels", levels)
        object.__setattr__(self, "background_label", background)
        if self.icc_profile is not None:
            object.__setattr__(self, "icc_profile", bytes(self.icc_profile))

    @property
    def samples_per_pixel(self) -> int:
        return 3 if self.image_type == "rgb" else 1

    @property
    def logical_channel_count(self) -> int:
        return len(self.channel_names)

    @property
    def sample_count(self) -> int:
        return self.logical_channel_count * self.samples_per_pixel

    def level(self, index: int) -> ImageLevel:
        index = integer(index, "level")
        if index >= len(self.levels):
            raise IndexError(f"Pyramid level {index} does not exist ({len(self.levels)} levels)")
        return self.levels[index]
